springdoc:
  swagger-ui:
    path: /swagger-ui.html

client:
  exchangeRates:
    url: http://api.exchangeratesapi.io/v1
    token: d370ffd97b514506749458d7ecbd775e

mongo:
  dbname: ${MONGO_DBNAME}
  urlconection: ${MONGO_URLCONECTION}
